# Set nginx base image
FROM nginx:stable-alpine
ARG nginx_conf
# Copy a configuration file from the current directory
RUN echo $nginx_conf
COPY nginx.conf ./etc/nginx
# Expose ports
EXPOSE 80

# Set the default command to execute when creating a new container
CMD ["nginx", "-g", "daemon off;"]
