# Set nginx base image
FROM nginx:stable-alpine
ARG nginx_conf
# Copy a configuration file from the current directory
RUN echo $nginx_conf
COPY ./prod/nginx.conf ./etc/nginx
RUN mkdir -p /var/www/html/public
COPY ./public ./var/www/html/public
# Expose ports
EXPOSE 80

# Set the default command to execute when creating a new container
CMD ["nginx", "-g", "daemon off;"]
